[2015-07-25 03:12:03] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:87 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(87): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 87, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:12:48] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:87 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(87): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 87, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:12:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot access protected property Doctrine\DBAL\Schema\Column::$_name' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:14:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot access protected property Doctrine\DBAL\Schema\Column::$_name' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:14:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot access protected property Doctrine\DBAL\Schema\Column::$_name' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:25:47] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:07] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:07] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:26:07] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:27:44] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function get() on array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:63 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:29:17] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:30:00] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Doctrine\DBAL\Schema\Column as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:70 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:30:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Doctrine\DBAL\Schema\Column as array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:70 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:33:38] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:41:52] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Schema\MySqlBuilder::getColumnListing()' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:206 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 03:42:59] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:45:10] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:88 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 88, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:45:18] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:89 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(89): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 89, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:45:39] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:89 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(89): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 89, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 03:46:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:89 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(89): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 89, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 04:05:38] log.ERROR: exception 'ErrorException' with message 'Undefined variable: response' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:95 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(95): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/Applications/X...', 95, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 04:29:31] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class name must be a valid object or a string' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:84 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 04:31:33] log.ERROR: exception 'ErrorException' with message 'Illegal string offset 'status'' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:91 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(91): Illuminate\Exception\Handler->handleError(2, 'Illegal string ...', '/Applications/X...', 91, Array) #1 [internal function]: WebusuarioController->store() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 04:46:23] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:46:40] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:46:41] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:46:41] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:46:41] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:46:42] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:03] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:06] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:10] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:16] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:22] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:41] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:42] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:42] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:42] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:42] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:50:43] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:53:06] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 04:53:17] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-07-25 04:53:27] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Routing\Router::group() must be of the type array, string given, called in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 209 and defined' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:646 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(646): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', '/Applications/X...', 646, Array) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(209): Illuminate\Routing\Router->group('usuarios', 'WebusuarioContr...') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/routes.php(26): Illuminate\Support\Facades\Facade::__callStatic('group', Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/routes.php(26): Illuminate\Support\Facades\Route::group('usuarios', 'WebusuarioContr...') #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/start.php(253): require('/Applications/X...') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/bootstrap/start.php(61): require('/Applications/X...') #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(35): require_once('/Applications/X...') #7 {main} [] []
[2015-07-25 04:53:27] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Routing\Router::group() must be of the type array, string given, called in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 209 and defined' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:646 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(646): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', '/Applications/X...', 646, Array) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(209): Illuminate\Routing\Router->group('usuarios', 'WebusuarioContr...') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/routes.php(26): Illuminate\Support\Facades\Facade::__callStatic('group', Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/routes.php(26): Illuminate\Support\Facades\Route::group('usuarios', 'WebusuarioContr...') #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/start.php(253): require('/Applications/X...') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/bootstrap/start.php(61): require('/Applications/X...') #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(35): require_once('/Applications/X...') #7 {main} [] []
[2015-07-25 04:58:17] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-07-25 04:58:18] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-07-25 05:09:54] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-07-25 05:20:36] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-07-25 05:21:28] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-07-25 05:21:48] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:974 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Applications/X...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2015-07-25 05:26:37] log.ERROR: exception 'LogicException' with message 'Route pattern "/generic/{table}/id/{id}/{{id}}" cannot reference variable name "id" more than once.' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php:102 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/RouteCompiler.php(57): Symfony\Component\Routing\RouteCompiler::compilePattern(Object(Illuminate\Routing\Route), '/generic/{table...', false) #1 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Route.php(586): Symfony\Component\Routing\RouteCompiler::compile(Object(Illuminate\Routing\Route)) #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(108): Symfony\Component\Routing\Route->compile() #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php(85): Symfony\Component\Routing\Matcher\UrlMatcher->matchCollection('/usuarios', Object(Symfony\Component\Routing\RouteCollection)) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1042): Symfony\Component\Routing\Matcher\UrlMatcher->match('/usuarios') #5 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #9 {main} [] []
[2015-07-25 19:38:11] log.ERROR: exception 'ErrorException' with message 'Cannot use a scalar value as an array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:160 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(160): Illuminate\Exception\Handler->handleError(2, 'Cannot use a sc...', '/Applications/X...', 160, Array) #1 [internal function]: WebusuarioController->destroy('3') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('destroy', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'destroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3') #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 19:38:48] log.ERROR: exception 'ErrorException' with message 'Cannot use a scalar value as an array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:160 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(160): Illuminate\Exception\Handler->handleError(2, 'Cannot use a sc...', '/Applications/X...', 160, Array) #1 [internal function]: WebusuarioController->destroy('2') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('destroy', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'destroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2') #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 19:38:52] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function delete() on null' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:154 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2015-07-25 19:38:57] log.ERROR: exception 'ErrorException' with message 'Cannot use a scalar value as an array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:160 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(160): Illuminate\Exception\Handler->handleError(2, 'Cannot use a sc...', '/Applications/X...', 160, Array) #1 [internal function]: WebusuarioController->destroy('4') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('destroy', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'destroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('4') #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-07-25 19:39:09] log.ERROR: exception 'ErrorException' with message 'Cannot use a scalar value as an array' in /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php:160 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/app/controllers/WebusuarioController.php(160): Illuminate\Exception\Handler->handleError(2, 'Cannot use a sc...', '/Applications/X...', 160, Array) #1 [internal function]: WebusuarioController->destroy('17') #2 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('destroy', Array) #4 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'destroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('17') #6 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /Applications/XAMPP/xamppfiles/htdocs/xtreme_colegios/api/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
